config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  get 'products/product_json'
  get 'categories/category_json'
  

  resources :categories do
    resources :products
  end

  resources :products
  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    cat ={'categories' => @categories}
    respond_to do |format|
      format.json { render json: cat }
      format.html
    end
  end

  def show
    begin
      @category = Category.find(params[:id])
      cat ={'category' => @category}
      respond_to do |format|
        format.json { render json: cat}
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      not_found
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html {
          redirect_to @category
        }
        format.json {
          render json: @category
        }
      else
        format.html {
          render 'new'
        }
        format.json {
          render json: @category.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to @category
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:category_id]
      @products = Product.where(:category_id => params[:category_id])
    else
      @products = Product.all
    end
    product_json = JSON.parse(@products.to_json(:include => { :category => { :only => :title } }))
    respond_to do |format|
      format.json { render json: {'products' => product_json} }
      format.html
    end
  end

  def show
    begin
      @product = Product.find(params[:id])
      product_json = JSON.parse(@product.to_json(:include => { :category => { :only => :title } }))
      respond_to do |format|
        format.json { render json: {'product' => product_json}}
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      not_found
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html {
          redirect_to @product
        }
        format.json {
          render json: @product
        }
      else
        format.html {
          render 'new'
        }
        format.json {
          render json: @product.errors, status: :unprocessable_entity
        }
      end
    end

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to @product
  end

  def product_item
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:title, :price, :text, :picture, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@categories = Category.all
  	@products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, html: {class: 'form-horizontal'} do |f| %>
    <%= link_to 'Back', categories_url %>
    <div class="form-group">
      <%= f.label :title, 'Категория', class: 'col-md-3 col-sm-3 col-xs-12 control-label' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-3 col-sm-offset-3 col-xs-offset-12 col-md-6 col-sm-6 col-xs-12">
        <%= f.submit 'Сохранить', class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<% provide :page_title, 'Редактирование категории - ' + @category.title %>
<%= render 'form' %>

app/views/categories/index.html.erb
<% provide :page_title, 'Категория' %>
<%= link_to 'Создать категорию', new_category_url %>

<div class="form-horizontal">
  <div class="col-md-6 col-sm-6 col-xs-12">
    <table class="table table-hover col-sm-12">
      <thead>
      <tr>
        <th class="col-sm-4">Title</th>
        <th class="col-sm-2">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @categories.each do |category| %>
          <tr>
            <td><%= category.title %></td>
            <td>
              <%= link_to 'View, ', category_url(category) %>
              <%= link_to 'Edit, ', edit_category_url(category) %>
              <%= link_to 'Remove', category_url(category),
                          method: :delete,
                          data: {confirm: 'Вы действительно хотите удалить эту категорию?'} %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<% provide :page_title, 'Новая категория' %>
<%= render 'form' %>

app/views/categories/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit, ', edit_category_url(@category) %>
<%= link_to 'Remove', category_url(@category),
            method: :delete,
            data: {confirm: 'Вы действительно хотите удалить этот товар?'} %>

app/views/layouts/_navbar.html.erb
	<ul>
		<li><a href="<%= categories_path %>">Все категории</a></li>
		<li><a href="<%= products_path %>">Все продукты</a></li>
		<li><a href="<%= products_path(:format => 'json') %>">Все продукты  json</a></li>
		<li><a href="<%= categories_path(:format => 'json')  %>">Все категории json</a></li>
		<li><a href="<%= new_category_path %>">Создать категорию</a></li>
		<li><a href="<%= new_product_path %>">Создать товар</a></li>
	</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Catalog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand text-center" href="/">Главная</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="<%= categories_path %>">Все категории</a></li>
          <li><a href="<%= products_path %>">Все товары</a></li>
          <li><a href="<%= products_path(:format => 'json') %>">Все товары  json</a></li>
          <li><a href="<%= categories_path(:format => 'json')  %>">Все категории json</a></li>
          <li><a href="<%= new_category_path %>">Создать категорию</a></li>
          <li><a href="<%= new_product_path %>">Создать продукт</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">

    <%= bootstrap_flash %>
    <%= yield %>
  </div><!-- /.container -->

  <footer class="footer">
    <div class="container text-center">
      <p class="text-muted">Все права защищены и даже сохранены в облаке! <br> &copy; Бишкек 2016</p>
    </div>
  </footer>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: {class: 'form-horizontal'} do |f| %>
    <%= link_to 'Back', products_url %>

    <div class="form-group">
      <%= f.label :period, value: 'Выберите категорию*', class: 'col-md-3 col-sm-3 col-xs-12 control-label' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.collection_select :category_id, Category.all.order(created_at: :desc), :id, :title, {},
                                autofocus: true, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :title %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :title, 'Товар', class: 'col-md-3 col-sm-3 col-xs-12 control-label' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :picture, 'Фото*', class: 'col-md-3 col-sm-3 col-xs-12 control-label' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.file_field :picture, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :text, 'Описание', class: 'col-md-3 col-sm-3 col-xs-12 control-label' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :text, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, 'Цена', class: 'col-md-3 col-sm-3 col-xs-12 control-label' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-3 col-sm-offset-3 col-xs-offset-12 col-md-6 col-sm-6 col-xs-12">
        <%= f.submit 'Сохранить', class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<% provide :page_title, 'Редактирование товара - ' + @product.title %>
<%= render 'form' %>

app/views/products/index.html.erb
<% provide :page_title, 'Товар' %>
<%= link_to 'Создать товар', new_product_url %>

<div class="form-horizontal">
  <div class="col-md-6 col-sm-6 col-xs-6">
    <table class="table table-hover col-sm-6">
      <thead>
      <tr>

        <th class="col-sm-4">Category</th>
        <th class="col-sm-4">Title</th>
        <th class="col-sm-4">Picture</th>
        <th class="col-sm-4">Text</th>
        <th class="col-sm-4">Price</th>
        <th class="col-sm-4">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @products.each do |product| %>
          <tr>

            <td><%= product.category.title %></td>
            <td><%= product.title %></td>
            <td><%= image_tag product.picture.url, width:'100'%></td>
            <td><%= product.text %></td>
            <td><%= product.price %></td>
            <td>

              <%= link_to 'View, ', product_url(product) %>
              <%= link_to 'Edit, ', edit_product_url(product) %>
              <%= link_to 'Remove', product_url(product),
                          method: :delete,
                          data: {confirm: 'Вы действительно хотите удалить этот товар?'} %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/new.html.erb
<% provide :page_title, 'Новый товар' %>
<%= render 'form' %>

app/views/products/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @product.category.title %>
</p>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Picture:</strong>
  <img src='<%= @product.picture.url %>' width="200" height='200'>
</p>
<p>
  <strong>Text:</strong>
  <%= @product.text %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit, ', edit_product_url(@product) %>
<%= link_to 'Remove', product_url(@product),
            method: :delete,
            data: {confirm: 'Вы действительно хотите удалить этот товар?'} %>

app/views/shared/_field_errors.html.erb
<% object.errors[field_name].each do |error| %>
    <div class="error-message"><%= error %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Все товары</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Image</th>
    <th>Text</th>
    <th>Price</th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td> <%= link_to Product.find(product).title %></td>
        <td> <img src='<%= product.picture.url %>' width="200" height='200'></td>
        <td><%= product.text %></td>
        <td><%= product.price %> сом</td>
      </tr>
  <% end %>
</table>